import json
import os

# Load the optimized parameters generated by train_model.py
PARAMS_FILE = os.path.join(os.path.dirname(__file__), "optimal_params.json")

def load_parameters():
    """Loads the ML-optimized physics parameters."""
    try:
        with open(PARAMS_FILE, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print("Error: optimal_params.json not found. Run train_model.py first.")
        return None

def predict_race(race_data):
    """
    Predicts the finishing order of a new race using the Golden Formula.
    """
    params = load_parameters()
    if not params: return []

    # Extract shared race settings used in lap simulation.
    config = race_data['race_config']
    laps = config['total_laps']
    base_t = config['base_lap_time']
    pit_t = config['pit_lane_time']
    tf = config['track_temp'] / 30.0
    
    # Apply generalized percentages
    offs = {'SOFT': 0.0, 'MEDIUM': base_t * params["O_M"], 'HARD': base_t * params["O_H"]}
    degs = {'SOFT': base_t * params["D_S"], 'MEDIUM': base_t * params["D_M"], 'HARD': base_t * params["D_H"]}
    pos_penalty = base_t * params["P_Pos"]
    
    # Collect total simulated race time for each driver.
    results = []
    
    for pos_str, strategy in race_data['strategies'].items():
        pos_idx = int(pos_str.replace('pos', ''))
        driver = strategy['driver_id']
        tire = strategy['starting_tire']
        pit_stops = { p['lap']: p['to_tire'] for p in strategy['pit_stops'] }
        
        # Apply starting-grid penalty before lap simulation.
        total_time = (pos_idx - 1) * pos_penalty 
        tire_age = 0
        
        # Simulate lap by lap physics
        for l in range(1, laps + 1):
            if l in pit_stops:
                total_time += pit_t 
                tire = pit_stops[l] 
                tire_age = 0         
            
            lap_time = base_t + offs[tire] + (degs[tire] * tire_age * tf)
            total_time += lap_time
            tire_age += 1
            
        results.append((total_time, driver))
        
    # Sort from lowest time (winner) to highest time
    results.sort()
    return [r[1] for r in results]

# Example Usage:
if __name__ == "__main__":
    # Test with a dummy input
    test_json = """
    {
      "race_config": {"track": "Test", "total_laps": 31, "base_lap_time": 84.3, "pit_lane_time": 21.4, "track_temp": 32},
      "strategies": {
        "pos1": {"driver_id": "D001", "starting_tire": "MEDIUM", "pit_stops": [{"lap": 17, "from_tire": "MEDIUM", "to_tire": "HARD"}]}
      }
    }
    """
    dummy_data = json.loads(test_json)
    prediction = predict_race(dummy_data)
    print("Predicted Finishing Order:", prediction)